---

- name: Setup ansible_sudo_pass
  gather_facts: no
  hosts: azure
  tasks:
    - name: Set ansible_sudo_pass
      set_fact:
        ansible_sudo_pass: "{{user_password}}"
    - name: Set ansible_become_password
      set_fact:
        ansible_become_password: "{{user_password}}"

- hosts: azure
  become_user: root
  become: true
  become_method: sudo
  vars:
    max_gap_kb: 1024
  tasks:
    - name: install required packages
      dnf: name={{ item }}
      with_items:
        - parted
        - e2fsprogs
        - cloud-utils-growpart
    - name: find PV
      command: 'pvdisplay -C --reportformat json'
      register: pvlist
      failed_when: "pvlist.rc != 1 and pvlist.rc != 0"
    - name: set full dev
      set_fact:
        devFull: "{{ (pvlist.stdout | from_json)['report'][0]['pv'][0]['pv_name'] }}"
    - name: set dav attributes
      set_fact:
        dev: "{{ devFull | regex_replace('[0-9]', '')}}"
        part: "{{ devFull | regex_replace('[^0-9]', '')}}"
    - name: partition info
      parted:
        device: "{{dev}}"
        number: "{{part}}"
      register: partinfo
    - set_fact:
        gap_kb: "{{partinfo.disk.size - partinfo.partitions[(vars.part | int)-1].end}}"
    - debug: 'msg="Gap after partition {{part}}: {{gap_kb}}kiB"'
    - name: grow too small partition to maximum
      command: 'growpart {{ dev }} {{ part }}'
      when: max_gap_kb < gap_kb|int
      register: growpartres
      failed_when: "growpartres.rc != 1 and growpartres.rc != 0"
    - name: grow pv
      shell: pvresize "{{dev}}{{part}}"
    - name: grow lv
      shell: lvextend  /dev/rootvg/rootlv "{{dev}}{{part}}" -r
      register: growlvres
      failed_when: "growlvres.rc != 5 and growlvres.rc != 0"
