---
- name: Setup CentOS
  hosts: azure
  become_user: root
  become: true
  become_method: sudo
  tasks:
    - name: Install libselinux as prerequisite for SELinux Ansible module
      yum:
        name: "{{item}}"
        state: latest
      with_items:
        - libselinux-python
        - libsemanage-python

    - name: Disable SELinux at next reboot
      selinux:
        state: disabled

    - name: Set SELinux in permissive mode until the machine is rebooted
      command: setenforce 0
      ignore_errors: true
      changed_when: false

    - name: Copy SSH keys to root
      authorized_key:
        user: root
        key: "{{item}}"
      with_items: "{{ssh_public_keys}}"

    - name: Add IP address of all hosts to all hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_host }} {{item}} {{ hostvars[item].host_alias | default('') }}"
        state: present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.all }}"
