---

- name: Setup ansible_sudo_pass
  gather_facts: no
  hosts: azure
  tasks:
    - name: Set ansible_sudo_pass
      set_fact:
        ansible_sudo_pass: "{{user_password}}"
    - name: Set ansible_become_password
      set_fact:
        ansible_become_password: "{{user_password}}"

- name: Setup CentOS
  hosts: azure
  become_user: root
  become: true
  become_method: sudo
  tasks:
    - name: Install libselinux as prerequisite for SELinux Ansible module
      yum:
        name: "{{item}}"
        state: latest
      with_items:
        - libselinux-python
        - libsemanage-python

    - name: Disable SELinux at next reboot
      selinux:
        state: disabled

    - name: Set SELinux in permissive mode until the machine is rebooted
      command: setenforce 0
      ignore_errors: true
      changed_when: false

    - name: Copy SSH keys to root
      authorized_key:
        user: root
        key: "{{lookup('file', item)}}"
      with_fileglob:
        - "{{ssh_public_keys_dir}}/*.pub"

    - name: Add IP address of all hosts to all hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_host }} {{item}} {{ hostvars[item].host_alias | default('') }}"
        state: present
      when: hostvars[item].ansible_host is defined
      with_items: "{{ groups.all }}"
